export enum NotificationType {
  PROJECT_ASSIGNED = "PROJECT_ASSIGNED",
  USER_ADDED_TO_PROJECT = "USER_ADDED_TO_PROJECT",
  STORY_ASSIGNED = "STORY_ASSIGNED",
  STORY_COMPLETED = "STORY_COMPLETED",
  SUBTASK_ASSIGNED = "SUBTASK_ASSIGNED",
  SUBTASK_STATUS_CHANGED = "SUBTASK_STATUS_CHANGED",
  COMMENT_ADDED = "COMMENT_ADDED",
  MEETING_SCHEDULED = "MEETING_SCHEDULED",
  MEETING_REMINDER = "MEETING_REMINDER",
  MEETING_STARTED = "MEETING_STARTED",
  MEETING_ENDED = "MEETING_ENDED",
  SPRINT_CREATED = "SPRINT_CREATED",
  COMPANY_REGISTERED = "COMPANY_REGISTERED"
}