export const BASE_API = {
	AUTH: "/api/auth",
	ADMIN: "/api/admin",
	SUPERADMIN: "/api/superadmin",
	PROJECT: "/api/project",
	USER_STORY: "/api/projects",
	SPRINT: "/api/project",
	SUBTASK: "/api/userstory",
	STANDUP: "/api/project/sprint",
	MEETING: "/api/meeting",
	GITHUB: "/api/github",
	USER_PROFILE: "/api/companies",
	NOTIFICATION: "/api/notifications",
	AI: "/api/ai",
	WORKLOG: "/api/worklogs",
	ANALYTICS: "/api/projects",
	REPORTS: "/api/projects",
};
